;;; markdownfmt-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from markdownfmt.el

(autoload 'markdownfmt-format-buffer "markdownfmt" "\
Format the current buffer using markdownfmt." t)
(autoload 'markdownfmt-enable-on-save "markdownfmt" "\
Run markdownfmt when saving buffer." t)
(register-definition-prefixes "markdownfmt" '("markdownfmt-"))

;;; End of scraped data

(provide 'markdownfmt-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; markdownfmt-autoloads.el ends here
