code --install-extension alexcvzz.vscode-sqlite
code --install-extension bodil.file-browser
code --install-extension bubersson.theme-hop-light
code --install-extension burkeholland.vs-code-can-do-that
code --install-extension capaj.vscode-exports-autocomplete
code --install-extension dbaeumer.vscode-eslint
code --install-extension dotjoshjohnson.xml
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension gerane.theme-solarized-light
code --install-extension github.vscode-pull-request-github
code --install-extension graphql.vscode-graphql
code --install-extension graphql.vscode-graphql-syntax
code --install-extension jacobdufault.fuzzy-search
code --install-extension kahole.magit
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension ms-azuretools.vscode-azureresourcegroups
code --install-extension ms-azuretools.vscode-cosmosdb
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.debugpy
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.azurecli
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension orta.vscode-jest
code --install-extension orta.vscode-react-native-storybooks
code --install-extension pflannery.vscode-versionlens
code --install-extension pkief.material-icon-theme
code --install-extension prisma.prisma
code --install-extension ryanolsonx.solarized
code --install-extension sdras.night-owl
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension vscodevim.vim
code --install-extension vspacecode.vspacecode
code --install-extension vspacecode.whichkey
code --install-extension wesbos.theme-cobalt2
